version: '3.9'

services:
  backend:
    build:
      context: ../
      dockerfile: docker/Dockerfile.dev
    container_name: coderank-backend-dev
    ports:
      - "3000:3000"
      - "5000:5000"
    environment:
      NODE_ENV: development
      PORT: 3000
      API_GATEWAY_PORT: 5000
      MONGODB_URI: mongodb+srv://vijay:yadav@backend-engineering.wu696s1.mongodb.net/quick-commerce?appName=Backend-Engineering
      JWT_SECRET: dev-secret-key-change-in-production
      LOG_LEVEL: debug
    volumes:
      - ../src:/app/src
      - ../config:/app/config
      - /app/node_modules
